"""
CLO Compliance AI - Configuration Package
"""

from .settings import (
    REGEX_PATTERNS,
    COMPLIANCE_THRESHOLDS,
    DOCUMENT_SECTIONS,
    PROMPT_TEMPLATES,
    API_CONFIG,
    DEFAULT_PATHS,
    LOG_CONFIG
)

__all__ = [
    'REGEX_PATTERNS',
    'COMPLIANCE_THRESHOLDS',
    'DOCUMENT_SECTIONS',
    'PROMPT_TEMPLATES',
    'API_CONFIG',
    'DEFAULT_PATHS',
    'LOG_CONFIG'
]
